replicaCount: 1

image:
  repository: ghcr.io/rianfowler/test-argocd-application/hello-world
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 'commit-14f6323'

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false

resources: {}

namespace: hello-world